import type { Monster, Move, PassiveAbility } from './types';

/**
 * Check if a monster is eligible to breed.
 * Eligible if: stage 3, OR stage 1 with no evolution path (evo_threshold_2 is null).
 */
export function canBreed(monster: Monster): boolean {
  if (!monster.gender) return false;
  if (monster.stage === 3) return true;
  if (monster.stage === 1 && monster.evo_threshold_2 === null) return true;
  return false;
}

/**
 * Check if two monsters can breed together.
 * Requires: both eligible, opposite genders, different monsters.
 */
export function canBreedTogether(
  a: Monster,
  b: Monster,
): { ok: boolean; reason?: string } {
  if (a.id === b.id)
    return { ok: false, reason: 'Cannot breed a monster with itself' };
  if (!canBreed(a))
    return {
      ok: false,
      reason: `${a.name} is not ready to breed (needs stage 3)`,
    };
  if (!canBreed(b))
    return {
      ok: false,
      reason: `${b.name} is not ready to breed (needs stage 3)`,
    };

  if (!a.gender || !b.gender) {
    return { ok: false, reason: 'Both monsters need a known gender to breed' };
  }

  if (a.gender === b.gender) {
    return { ok: false, reason: 'Both monsters are the same gender' };
  }

  return { ok: true };
}

/**
 * Determine which parent is mom/dad based on gender.
 */
export function getParents(
  a: Monster,
  b: Monster,
): { mother: Monster; father: Monster } {
  if (a.gender === 'female') return { mother: a, father: b };
  return { mother: b, father: a };
}

/**
 * Inherit moves from parents. Picks one move from each parent,
 * preferring moves with different effect types for variety.
 */
export function inheritMoves(mother: Monster, father: Monster): Move[] {
  const momMoves = mother.moves ?? [];
  const dadMoves = father.moves ?? [];

  if (momMoves.length === 0 && dadMoves.length === 0) return [];

  // Pick a random move from mom
  const momMove = momMoves[Math.floor(Math.random() * momMoves.length)];

  // Pick a move from dad, preferring a different effect type
  let dadMove = dadMoves.find((m) => m.effect !== momMove?.effect);
  if (!dadMove) {
    dadMove = dadMoves[Math.floor(Math.random() * dadMoves.length)];
  }

  const inherited: Move[] = [];
  if (momMove) inherited.push(momMove);
  if (dadMove) inherited.push(dadMove);

  return inherited;
}

/**
 * Inherit passive from one of the parents (50/50 chance).
 */
export function inheritPassive(
  mother: Monster,
  father: Monster,
): PassiveAbility | undefined {
  const momPassive = mother.passive;
  const dadPassive = father.passive;

  if (momPassive && dadPassive) {
    return Math.random() < 0.5 ? momPassive : dadPassive;
  }
  return momPassive ?? dadPassive;
}

/**
 * Generate blended stat hints for the offspring.
 * The actual stats are generated by GPT, but we provide base stat ranges.
 */
export function blendedStatHints(
  mother: Monster,
  father: Monster,
): Record<string, number> {
  const keys = ['hp', 'attack', 'defense', 'sp_attack', 'speed'] as const;
  const hints: Record<string, number> = {};

  for (const key of keys) {
    // Average of parents with ±10% variance, scaled down to stage 1 level
    const avg = (mother[key] + father[key]) / 2;
    const stage1Scale = 340 / 520; // stage 1 budget / stage 3 budget
    hints[key] = Math.round(avg * stage1Scale);
  }

  return hints;
}
